### ISSUE TITLE
add "requiredfiles_per_task" in benchmark.xml (especially for VCloud)

### ISSUE THREAD

**Issue by kfriedberger** [dbeyer/benchexec#20]
Instead of distributing all "requiredfiles" onto all workers (this runs in O(#files * #workers)!), it would be sufficient to send "requiredfiles_per_task" only to the worker for this task (this should need only O(#files)). This is beneficial for witness-checking, precision-re-usage, and everything related to re-using task-based information from a previous benchmark as input for new benchmark-tasks.

The substitution of the substring "${sourcefile_name}" in the "requiredfiles_per_task"-element has to be evaluated once per task.

This issue has to be implemented in benchexec first, then it can be used by other scripts based on benchexec. This issue also requires to modify the script vcloud.py at CPAchecker to simply write the "requiredfiles_per_task" at the end of the task-lines (just like an additional sourcefile, tab-separated). The VCloud itself does not need to be changed.

Example:
By replacing (1) by (2) the files would only be used for the task itself, because only there the name is matching (instead of the wildcard "*" that matches all files.

(1) `<requiredfiles>../../test/results/benchmark.2015-05-27_1105.logfiles/test.*.files/output.txt</requiredfiles>`
(2) `<requiredfiles_per_task>../../test/results/benchmark.2015-05-27_1105.logfiles/test.${sourcefile_name}.files/output.txt</requiredfiles_per_task>`

**Comment by kfriedberger** [comment]
Perhaps the new xml-tag "requiredfiles_per_task" is too much, because "requiredfiles" is already available on "rundefinition"-level. It does not allow substitution. Maybe implementing the task-based substitution of "${sourcefile_name}" might be enough?

Also vcloud.py has code for something like this. Documentation?

**Comment by PhilippWendler** [comment]
The latter suggestion of allowing to use `${inputfile_name}` etc. is now implemented for tags contained inside `<rundefinition>` and `<tasks>`.
If `<requiredfiles>` is used directly on the top level this is not done, to allow for a list of globally required files to be handled more efficiently instead of duplicating it per task.
