### ISSUE TITLE
Incorrect summary stats when modifying status column 'value'.

### ISSUE THREAD

**Issue by MontyCarter** [dbeyer/benchexec#24]
This is by no means necessary, and is a result of me modifying the output xml files, so I am not sure whether this should actually be changed as I suggest, or if there is perhaps another way to accomplish my goal.

To create an output like the final results on the svcomp webpage, setting the status column value to "witness confirmed", "witness timeout", etc breaks the stat counting on the new, more fine-grained results summary. (See attached image)

It looks like in tablegenerator/\_\_init\_\_.py, in the get_stats_of_run_set(), table-generator determines whether each item was supposed to be true or false by using the status column directly if CATEGORY is CORRECT, and negating the status column if CATEGORY was WRONG.

As a result, if the status column 'value' isn't in results.py's RESULT_LIST, the result won't count towards any of the four combinations of correct/incorrect true/false.

If expected results were generated using the sourcefile's name and associated property file (using satisfies_property_file, I think), then it wouldn't matter what value is in the status column's value field, and the counting for things like this would work.

Attached is an example of where this is problematic for me.  The two benchexec runsets are actually the same run, however, one has had all false files witness checked.  Notice that the scores are the same, but correct/incorrect counts are not identical.

![image](https://cloud.githubusercontent.com/assets/4269524/7994853/1158fa4a-0ace-11e5-9605-e890bd3c7343.png)

**Comment by PhilippWendler** [comment]
Thanks for reporting this. The change in handling results was necessary to be able to handle to results more flexibly, for example results for which no score should be computed.

I am not exactly sure whether (and how) witness checking can or should be integrated directly in BenchExec, and this will probably get developed only over time when we get more practice with witnesses. However, for now an easy solution is to simply accept `witness confirmed` as an additional valid tool result, so your use case works.
