### ISSUE TITLE
Direct plot with "correct results only" does not work

### ISSUE THREAD

**Issue by cheshire** [dbeyer/benchexec#27]
http://buildbot.sosy-lab.org/results/integration-policyIteration/1767.-r17671%23integration-policyIteration.2015-08-24_1806.results.html
Click on abstraction time -> direct plot -> correct results only.
Maybe I'm doing something wrong, but I always get this result on all result sets I get.

**Comment by PhilippWendler** [comment]
The problem happens only if the first row of the table does not contain a correct result. This will be fixed.

As temporary workaround, use "Filter Rows" to select only rows with status `correct` before showing the plot.
