### ISSUE TITLE
--offline option does not work for javascript

### ISSUE THREAD

**Issue by cheshire** [dbeyer/benchexec#29]
(or I don't understand it correctly).

The python code says that if "--offline" is passed in, instead of CDN URL, the local URL is used for JS libraries, yet no JS libraries are contained in the repository?..
Should we choose to package some (reasonable?) version of jQuery/etc together with benchexec?

**Comment by PhilippWendler** [comment]
The intention of this flag is to create an HTML file that you can package together with the JavaScript libraries in a archive such that for example reviewers are able to view it offline. It is not intended to actually package it together. If there is enough interest, we could bundle a script that downloads the necessary files, but I wouldn't add them to the repository.
