### ISSUE TITLE
permission to add wrapper script for hiprec

### ISSUE THREAD

**Issue by lequangloc** [dbeyer/benchexec#77]
Dear Dirk Beyer,
I am Le Quang Loc, from NUS- SIngapore. This year, our team participate SVCOMP with hiprec.

May I ask you the permission to commit a wrapper into the project?

Thank you,
Loc

**Comment by PhilippWendler** [comment]
Dear Loc,

please open a [pull request](https://github.com/dbeyer/benchexec/pulls) for your tool wrapper.

Kind regards,
Philipp Wendler

**Comment by lequangloc** [comment]
Dear Philipp Wendler,
My colleague has done.

Many thanks,
Loc
